version: '3'

services:
  arangodb:
    image: arangodb:3.1.10
    restart: always
    ports:
      - 8529:8529
    volumes:
      - .data/arangodb:/var/lib/arangodb:rw
      - .data/arangodb3:/var/lib/arangodb3:rw
      - .data/arangodb3-apps:/var/lib/arangodb3-apps:rw
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      